<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    
  </PropertyGroup>
  <ItemGroup>
    <None Remove="sql\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="sql\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\theredhead.text\theredhead.text.csproj" />
  </ItemGroup>
</Project>
